name: Trigger a cluster test on a PR
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
  issues: read
  pull-requests: read
  id-token: write

jobs:

  get_head:
    runs-on: self-hosted-docker-tiny
    outputs:
      sha: ${{ steps.get_head.outputs.sha }}
      repo: ${{ steps.get_head.outputs.repo }}
    steps:
      - name: Get head SHA & repo
        id: get_head
        run: |
          query='query pullRequestDetails { repository(name: "${{ github.event.repository }}", owner: "${{ github.event.organization }}") { pullRequest(number: ${{ github.event.issue.number }}) { headRef { target { oid } } headRepository { sshUrl } } } }'
          result=$(gh api graphql -F query="$query")
          sha=$(echo "$result" | jq -r '.data.repository.pullRequest.headRef.target.oid')
          repo=$(echo "$result" | jq -r '.data.repository.pullRequest.headRepository.sshUrl')

  trigger_cluster_test_basic:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/cluster_test')
    needs: get_head
    uses: ./.github/workflows/cluster_tests.yml
    secrets: inherit
    with:
      workflow: cluster_test
      sha: ${{ needs.get_head.outputs.sha }}
      splice_url: ${{ needs.get_head.outputs.repo }}

  result:
    runs-on: self-hosted-docker-tiny
    needs:
      - trigger_cluster_test_basic
      - get_head
    steps:
      - run: |
          number=$(echo '${{ needs.trigger_cluster_test_basic.outputs.result }}' | jq -r '.number')
          echo "Deploy scratchnet pipeline triggered for [commit ${{ needs.get_head.outputs.sha }} in ${{ needs.get_head.outputs.repo }}](https://github.com/${{ github.repository }}/pull/${{ github.event.issue.number }}/files/${{ needs.get_head.outputs.sha }}), please approve it in CircleCI: https://app.circleci.com/pipelines/github/DACH-NY/canton-network-internal/${number}"


  trigger_cluster_test_hdm:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/hdm_test')
    needs: get_sha
    uses: ./.github/workflows/cluster_tests.yml
    secrets: inherit
    with:
      workflow: hdm_test
      sha: ${{ needs.get_sha.outputs.sha }}

  result_hdm:
    runs-on: self-hosted-docker-tiny
    needs:
      - trigger_cluster_test_hdm
      - get_sha
    steps:
      - run: |
          number=$(echo '${{ needs.trigger_cluster_test_hdm.outputs.result }}' | jq -r '.number')
          echo "Deploy scratchnet HDM pipeline triggered for [PR as of ${{ needs.get_sha.outputs.sha }}](https://github.com/${{ github.repository }}/pull/${{ github.event.issue.number }}/files/${{ needs.get_sha.outputs.sha }}), please approve it in CircleCI: https://app.circleci.com/pipelines/github/DACH-NY/canton-network-internal/${number}"
