name: CI on PRs from forks
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches: [ main ] # Only run on PRs with `main` as their base

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # Required for GCP Workload Identity for failure notifications
  contents: read
  pull-requests: read # Required for the static tests
  issues: read # Required for the static tests
  actions: write # To cancel itself if not opted in

jobs:
  ci:
    uses: ./.github/workflows/build.yml
    if: (github.repository != 'DACH-NY/canton-network-node') && (github.repository != 'hyperledger-labs/splice')
    secrets: inherit
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
