on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  hello_world:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Hello world
        run: echo "Hello, world!"
