on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  hello_world_2:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Hello world 2
        run: echo "Hello, world 1!"
