on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  env_hold:
    name: "Approve CI for Forks"
    environment: ci-forks
    runs-on: self-hosted-docker-tiny
    steps:
      - name: Wait for environment approval for runs from forks
        run: exit 0

  hello_world:
    uses: ./.github/workflows/reusable.yml
    needs: env_hold
