on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  env_hold:
    environment: ci-forks
    runs-on: self-hosted-docker-tiny
    if: github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Wait for environment approval for runs from forks
        run: exit 0

  hello_world:
    uses: ./.github/workflows/reusable.yml
    needs: env_hold
