on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  hello_world:
    uses: ./.github/workflows/reusable.yml
    if: (github.repository == 'DACH-NY/canton-network-node') || (github.repository == 'hyperledger-labs/splice')
